import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  ManyToOne,
  JoinColumn,
  Index,
} from 'typeorm';
import { Project } from './project.entity';
import { User } from './user.entity';

export type RoadmapStatus =
  | 'proposed'
  | 'approved'
  | 'planned'
  | 'in_progress'
  | 'completed'
  | 'rejected';

export type RoadmapPriority = 'low' | 'medium' | 'high' | 'critical';

export type RoadmapEffort = 'xs' | 's' | 'm' | 'l' | 'xl';

@Entity('roadmap_items')
export class RoadmapItem {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Column({ type: 'uuid' })
  @Index()
  projectId!: string;

  @ManyToOne(() => Project, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'projectId' })
  project!: Project;

  @Column({ type: 'varchar', length: 220 })
  title!: string;

  @Column({ type: 'text' })
  problem!: string;

  @Column({ type: 'text', nullable: true })
  outcome?: string;

  @Column({ type: 'varchar', length: 20, default: 'medium' })
  priority!: RoadmapPriority;

  @Column({ type: 'varchar', length: 10, default: 'm' })
  effort!: RoadmapEffort;

  @Column({ type: 'varchar', length: 20, default: 'proposed' })
  status!: RoadmapStatus;

  @Column({ type: 'varchar', length: 16, nullable: true })
  targetQuarter?: string;

  @Column({ type: 'float', nullable: true })
  aiConfidence?: number;

  @Column({ type: 'text', nullable: true })
  aiRationale?: string;

  @Column({ type: 'jsonb', default: [] })
  sourceFeedbackIds!: string[];

  @Column({ type: 'boolean', default: false })
  autoGenerated!: boolean;

  @Column({ type: 'text', nullable: true })
  latestTaskPrompt?: string;

  @Column({ type: 'jsonb', nullable: true })
  latestTaskChecklist?: Array<{
    title: string;
    description: string;
    acceptanceCriteria: string[];
  }>;

  @Column({ type: 'uuid', nullable: true })
  ownerId?: string;

  @ManyToOne(() => User, { nullable: true, onDelete: 'SET NULL' })
  @JoinColumn({ name: 'ownerId' })
  owner?: User;

  @Column({ type: 'uuid', nullable: true })
  createdById?: string;

  @ManyToOne(() => User, { nullable: true, onDelete: 'SET NULL' })
  @JoinColumn({ name: 'createdById' })
  createdBy?: User;

  @Column({ type: 'jsonb', default: {} })
  metadata!: Record<string, unknown>;

  @CreateDateColumn()
  createdAt!: Date;

  @UpdateDateColumn()
  updatedAt!: Date;
}
